# Generated by Django 3.2.6 on 2021-08-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('profile_picture', models.FileField(default='default_pic.jpg', null=True, upload_to='')),
                ('facebook_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('instagram_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('youtube_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email_address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('custom_link_1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('custom_link_2', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=50, null=True)),
                ('order_details', models.JSONField(default=dict, null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_email', models.CharField(max_length=50, null=True)),
                ('customer_phoneNo', models.CharField(max_length=60, null=True)),
                ('customer_address', models.TextField(null=True)),
                ('customer_pinCode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(null=True, upload_to='')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_of_artist', to='mainwebsite.artists')),
            ],
        ),
    ]
