# Generated by Django 3.2.6 on 2021-08-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='ArtworkSize',
        ),
    ]
