# Generated by Django 3.2.6 on 2021-08-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0002_rename_size_artworksize'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='ketto_transaction_details',
            field=models.CharField(default='Not Provided', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
