# Generated by Django 3.2.6 on 2021-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0004_alter_orderhistory_ketto_transaction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artists',
            name='instagram_link2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
