# Generated by Django 3.2.6 on 2021-08-28 14:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0005_auto_20210819_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='sizes_available',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, '10x10'), (3, '20x20'), (4, '29x14.5'), (5, '42,21'), (6, 'A3'), (7, 'A4'), (8, 'A5')], max_length=13, null=True),
        ),
    ]
