# Generated by Django 3.2.6 on 2021-08-28 15:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0006_artwork_sizes_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sizes_available',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, '10x10'), (3, '20x20'), (4, '29x14.5'), (5, '42x21'), (6, 'A3'), (7, 'A4'), (8, 'A5'), (9, 'A6')], default=['2', '3', '4', '5', '6', '7', '8', '9'], max_length=15, null=True),
        ),
    ]
